name: "RC"

on:
  push:
    tags:
      - "v*-rc*"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get The Version
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          pull: true
          no-cache: true
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
